title: "Marcelo Marfil"
author: "Marcelo Marfil"
description: "on the internets"
baseurl: ""
url: "https://mmarfil.com"
email: "marcelo@mmarfil.com"
microblog_user: "mmarfil"
permalink: "/:year/:month/:day/:title/"
relative_permalinks: false
paginate: 20
paginate_path: "/page/:num/"
timezone: America/Sao_Paulo

highlighter: "rouge"
markdown: "kramdown"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

plugins:
  - jekyll-sitemap
  - jekyll-paginate
