services:

  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose --livereload
    ports:
      - 4000:4000
    volumes:
      - /Users/marcelo/Developer/mmarfil.github.io:/srv/jekyll
    restart: always
